# Generated by Django 6.0.3 on 2026-03-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'option_text')},
        ),
    ]
